import strawberry
from enum import Enum

@strawberry.enum
class UserRole(Enum):
    ADMIN = "ADMIN"
    USER = "USER"
    SUPERUSER = "SUPERUSER" 

@strawberry.enum
class OrganizationPermission(str, Enum):
    MANAGE_MEMBERS = "MANAGE_MEMBERS"
    MANAGE_ROLES = "MANAGE_ROLES"
    VIEW_ORGANIZATION = "VIEW_ORGANIZATION"
    MANAGE_ORGANIZATION = "MANAGE_ORGANIZATION"
    VIEW_ANALYTICS = "VIEW_ANALYTICS"
    MANAGE_BILLING = "MANAGE_BILLING"
    MANAGE_SUBSCRIPTIONS = "MANAGE_SUBSCRIPTIONS"
    ACCESS_ISP_MANAGER = "ACCESS_ISP_MANAGER"
    VIEW_ISP_MANAGER_DASHBOARD = "VIEW_ISP_MANAGER_DASHBOARD"
    VIEW_ISP_MANAGER_PACKAGES = "VIEW_ISP_MANAGER_PACKAGES"
    MANAGE_ISP_MANAGER_PACKAGES = "MANAGE_ISP_MANAGER_PACKAGES"
    VIEW_ISP_MANAGER_CUSTOMERS = "VIEW_ISP_MANAGER_CUSTOMERS"
    MANAGE_ISP_MANAGER_CUSTOMERS = "MANAGE_ISP_MANAGER_CUSTOMERS"
    VIEW_ISP_MANAGER_STATIONS = "VIEW_ISP_MANAGER_STATIONS"
    MANAGE_ISP_MANAGER_STATIONS = "MANAGE_ISP_MANAGER_STATIONS"


@strawberry.enum
class OrganizationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    PENDING = "PENDING"
    ARCHIVED = "ARCHIVED"

@strawberry.enum
class OrganizationMemberStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    PENDING = "PENDING"

@strawberry.enum
class IspManagerCustomerStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"

@strawberry.enum
class BuildingType(str, Enum):
    APARTMENT = "APARTMENT"
    OFFICE = "OFFICE"
    SCHOOL = "SCHOOL"
    HOSPITAL = "HOSPITAL"
    RESIDENTIAL = "RESIDENTIAL"
    COMMERCIAL = "COMMERCIAL"
    INDUSTRIAL = "INDUSTRIAL"
    GOVERNMENT = "GOVERNMENT"
    OTHER = "OTHER"

@strawberry.enum
class StationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    MAINTENANCE = "MAINTENANCE"
    OFFLINE = "OFFLINE"
