export enum OrganizationPermissions {
  MANAGE_MEMBERS = "MANAGE_MEMBERS",
  MANAGE_ROLES = "MANAGE_ROLES",
  VIEW_ORGANIZATION = "VIEW_ORGANIZATION",
  MANAGE_ORGANIZATION = "MANAGE_ORGANIZATION",
  VIEW_ANALYTICS = "VIEW_ANALYTICS",
  MANAGE_BILLING = "MANAGE_BILLING",
  MANAGE_SUBSCRIPTIONS = "MANAGE_SUBSCRIPTIONS",
  ACCESS_ISP_MANAGER = "ACCESS_ISP_MANAGER",
  VIEW_ISP_MANAGER_DASHBOARD = "VIEW_ISP_MANAGER_DASHBOARD",
  VIEW_ISP_MANAGER_PACKAGES = "VIEW_ISP_MANAGER_PACKAGES",
  MANAGE_ISP_MANAGER_PACKAGES = "MANAGE_ISP_MANAGER_PACKAGES",
  VIEW_ISP_MANAGER_CUSTOMERS = "VIEW_ISP_MANAGER_CUSTOMERS",
  MANAGE_ISP_MANAGER_CUSTOMERS = "MANAGE_ISP_MANAGER_CUSTOMERS",
  VIEW_ISP_MANAGER_STATIONS = "VIEW_ISP_MANAGER_STATIONS",
  MANAGE_ISP_MANAGER_STATIONS = "MANAGE_ISP_MANAGER_STATIONS",
  VIEW_ISP_MANAGER_INVENTORY = "VIEW_ISP_MANAGER_INVENTORY",
  MANAGE_ISP_MANAGER_INVENTORY = "MANAGE_ISP_MANAGER_INVENTORY",
  VIEW_ISP_MANAGER_TICKETS = "VIEW_ISP_MANAGER_TICKETS",
  MANAGE_ISP_MANAGER_TICKETS = "MANAGE_ISP_MANAGER_TICKETS",
  // Mpesa Payment Integration Permissions
  VIEW_MPESA_CONFIG = "VIEW_MPESA_CONFIG",
  MANAGE_MPESA_CONFIG = "MANAGE_MPESA_CONFIG",
  VIEW_MPESA_TRANSACTIONS = "VIEW_MPESA_TRANSACTIONS",
  // SMS Integration Permissions
  VIEW_SMS_CONFIG = "VIEW_SMS_CONFIG",
  MANAGE_SMS_CONFIG = "MANAGE_SMS_CONFIG",
  // Customer Payments Permissions
  VIEW_CUSTOMER_PAYMENTS = "VIEW_CUSTOMER_PAYMENTS",
  MANAGE_CUSTOMER_PAYMENTS = "MANAGE_CUSTOMER_PAYMENTS",
  // Activity Permissions
  VIEW_ACTIVITY = "VIEW_ACTIVITY",
  CLEAR_ACTIVITY = "CLEAR_ACTIVITY",
}
