export enum OrganizationPermissions {
  MANAGE_MEMBERS = "MANAGE_MEMBERS",
  MANAGE_ROLES = "MANAGE_ROLES",
  VIEW_ORGANIZATION = "VIEW_ORGANIZATION",
  MANAGE_ORGANIZATION = "MANAGE_ORGANIZATION",
  VIEW_ANALYTICS = "VIEW_ANALYTICS",
  MANAGE_BILLING = "MANAGE_BILLING",
  MANAGE_SUBSCRIPTIONS = "MANAGE_SUBSCRIPTIONS",
  ACCESS_ISP_MANAGER = "ACCESS_ISP_MANAGER",
  VIEW_ISP_MANAGER_DASHBOARD = "VIEW_ISP_MANAGER_DASHBOARD",
  VIEW_ISP_MANAGER_PACKAGES = "VIEW_ISP_MANAGER_PACKAGES",
  MANAGE_ISP_MANAGER_PACKAGES = "MANAGE_ISP_MANAGER_PACKAGES",
  VIEW_ISP_MANAGER_CUSTOMERS = "VIEW_ISP_MANAGER_CUSTOMERS",
  MANAGE_ISP_MANAGER_CUSTOMERS = "MANAGE_ISP_MANAGER_CUSTOMERS",
  VIEW_ISP_MANAGER_STATIONS = "VIEW_ISP_MANAGER_STATIONS",
  MANAGE_ISP_MANAGER_STATIONS = "MANAGE_ISP_MANAGER_STATIONS"
}